version: 0.2

env:
  variables:
    AWS_REGION: AWS_REGION
    ECR_REPOSITORY: ECR_REPOSITORY
    AWS_ACCOUNT_ID: AWS_ACCOUNT_ID
    IMAGE_TAG: IMAGE_TAG
    NODE_OPTIONS: "--max-old-space-size=8192"
    BABEL_DISABLE_CACHE: "1"

phases:
  pre_build:
    commands:
      - echo "================= ENVIRONMENT VARIABLES ================="
      - echo "Region - $AWS_REGION"
      - echo "Repo - $ECR_REPOSITORY"
      - echo "Account ID - $AWS_ACCOUNT_ID"
      - echo "Image Tag (before assignment) - $IMAGE_TAG"
      - echo "========================================================="
      
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      
      - if [ -z "$IMAGE_TAG" ]; then IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7); fi
      - echo "Resolved Image Tag - $IMAGE_TAG"

      # Fetch parameters from SSM Parameter Store and write to .env file
      - echo "Fetching parameters from AWS SSM Parameter Store"

      # Fetch ADMIN_EMAIL parameter from Parameter Store
      # - REACT_APP_SUPERSET_BASE_URL=$(aws ssm get-parameter --name "/csight/frontend/REACT_APP_SUPERSET_BASE_URL" --with-decryption --query "Parameter.Value" --output text)
      # - echo "REACT_APP_SUPERSET_BASE_URL - $REACT_APP_SUPERSET_BASE_URL"
      - ADMIN_EMAIL=$(aws ssm get-parameter --name "/csight/frontend/ADMIN_EMAIL" --with-decryption --query "Parameter.Value" --output text)
      - echo "ADMIN_EMAIL - $ADMIN_EMAIL"
      - REACT_APP_LOGO_TEXT=$(aws ssm get-parameter --name "/csight/frontend/REACT_APP_LOGO_TEXT" --with-decryption --query "Parameter.Value" --output text)
      - echo "REACT_APP_LOGO_TEXT - $REACT_APP_LOGO_TEXT"
      # - REACT_APP_DWORKS_BASE_URL=$(aws ssm get-parameter --name "/csight/frontend/REACT_APP_DWORKS_BASE_URL" --with-decryption --query "Parameter.Value" --output text)
      # - echo "REACT_APP_DWORKS_BASE_URL - $REACT_APP_DWORKS_BASE_URL"
      - REACT_APP_DWORKS_API_KEY=$(aws ssm get-parameter --name "/csight/frontend/REACT_APP_DWORKS_API_KEY" --with-decryption --query "Parameter.Value" --output text)
      - echo "REACT_APP_DWORKS_API_KEY - $REACT_APP_DWORKS_API_KEY"
      - REACT_APP_INFO_MONTHLY_COST=$(aws ssm get-parameter --name "/csight/frontend/REACT_APP_INFO_MONTHLY_COST" --with-decryption --query "Parameter.Value" --output text)
      - echo "REACT_APP_INFO_MONTHLY_COST - $REACT_APP_INFO_MONTHLY_COST"\
      - REACT_APP_INFO_POTENTIAL_SAVINGS=$(aws ssm get-parameter --name "/csight/frontend/REACT_APP_INFO_POTENTIAL_SAVINGS" --with-decryption --query "Parameter.Value" --output text)
      - echo "REACT_APP_INFO_POTENTIAL_SAVINGS - $REACT_APP_INFO_POTENTIAL_SAVINGS"
      - REACT_APP_INFO_ALERTS=$(aws ssm get-parameter --name "/csight/frontend/REACT_APP_INFO_ALERTS" --with-decryption --query "Parameter.Value" --output text)
      - echo "REACT_APP_INFO_ALERTS - $REACT_APP_INFO_ALERTS"
      - REACT_APP_INFO_RECOMMENDATIONS=$(aws ssm get-parameter --name "/csight/frontend/REACT_APP_INFO_RECOMMENDATIONS" --with-decryption --query "Parameter.Value" --output text)
      - echo "REACT_APP_INFO_RECOMMENDATIONS - $REACT_APP_INFO_RECOMMENDATIONS"
      - REACT_APP_INFO_NEW_ASSETS=$(aws ssm get-parameter --name "/csight/frontend/REACT_APP_INFO_NEW_ASSETS" --with-decryption --query "Parameter.Value" --output text)
      - echo "REACT_APP_INFO_NEW_ASSETS - $REACT_APP_INFO_NEW_ASSETS"
      - REACT_APP_CSIGHT_API_URL=$(aws ssm get-parameter --name "/csight/frontend/REACT_APP_CSIGHT_API_URL" --with-decryption --query "Parameter.Value" --output text)
      - echo "REACT_APP_CSIGHT_API_URL - $REACT_APP_CSIGHT_API_URL"


      # Find the superset-frontend folder location in the repository and write parameters to .env file
      - echo "Writing parameters to .env file in superset-frontend folder"
      - ENV_FILE="$CODEBUILD_SRC_DIR/superset-frontend/.env"
      - echo "ADMIN_EMAIL=$ADMIN_EMAIL" > $ENV_FILE
      - echo "REACT_APP_LOGO_TEXT=$REACT_APP_LOGO_TEXT" >> $ENV_FILE
      # - echo "REACT_APP_DWORKS_BASE_URL=$REACT_APP_DWORKS_BASE_URL" >> $ENV_FILE
      - echo "REACT_APP_DWORKS_API_KEY=$REACT_APP_DWORKS_API_KEY" >> $ENV_FILE
      - echo "REACT_APP_INFO_MONTHLY_COST=$REACT_APP_INFO_MONTHLY_COST" >> $ENV_FILE
      - echo "REACT_APP_INFO_POTENTIAL_SAVINGS=$REACT_APP_INFO_POTENTIAL_SAVINGS" >> $ENV_FILE
      - echo "REACT_APP_INFO_ALERTS=$REACT_APP_INFO_ALERTS" >> $ENV_FILE
      - echo "REACT_APP_INFO_RECOMMENDATIONS=$REACT_APP_INFO_RECOMMENDATIONS" >> $ENV_FILE
      - echo "REACT_APP_INFO_NEW_ASSETS=$REACT_APP_INFO_NEW_ASSETS" >> $ENV_FILE
      - echo "REACT_APP_CSIGHT_API_URL=$REACT_APP_CSIGHT_API_URL" >> $ENV_FILE
      - cat $ENV_FILE  # Check if env contents copied successfully

  build:
    commands:
      # Check if the .env file exists before proceeding
      - if [ ! -f "$CODEBUILD_SRC_DIR/superset-frontend/.env" ]; then echo ".env file does not exist. Build will not proceed."; exit 1; fi
      - echo "Resolved Image Tag in build section - $IMAGE_TAG"
      - echo "Building the Docker image - $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG"
      - DOCKER_BUILDKIT=1 docker build --no-cache --build-arg NODE_OPTIONS="--max-old-space-size=8192" -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Pushing the image to Amazon ECR..."
      - echo "Resolved Image Tag in post_build section - $IMAGE_TAG"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
      - echo "Build and push completed successfully"

artifacts:
  files:
    - '**/*'
