version: 0.2

env:
  variables:
    AWS_REGION: AWS_REGION
    ECR_REPOSITORY: ECR_REPOSITORY
    AWS_ACCOUNT_ID: AWS_ACCOUNT_ID
    IMAGE_TAG: IMAGE_TAG

phases:
  pre_build:
    commands:
      - echo "================= ENVIRONMENT VARIABLES ================="
      - echo "Region - $AWS_REGION"
      - echo "Repo - $ECR_REPOSITORY"
      - echo "Account ID - $AWS_ACCOUNT_ID"
      - echo "Image Tag (before assignment) - $IMAGE_TAG"
      - echo "========================================================="
      
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      
      - if [ -z "$IMAGE_TAG" ]; then IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7); fi
      - echo "Resolved Image Tag - $IMAGE_TAG"

  build:
    commands:
      - echo "Resolved Image Tag in build section - $IMAGE_TAG"
      - echo "Building the Docker image - $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG"
      - DOCKER_BUILDKIT=1 docker build --build-arg NODE_OPTIONS="--max-old-space-size=8192" \
        -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Pushing the image to Amazon ECR..."
      - echo "Resolved Image Tag in post_build section - $IMAGE_TAG"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
      - echo "Build and push completed successfully"

artifacts:
  files:
    - '**/*'
