steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ts-cloud-factory-poc/dworks:2.1.0.v3','.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ts-cloud-factory-poc/dworks:2.1.0.v3']
timeout: 9000s
options:
 machineType: N1_HIGHCPU_32
 diskSizeGb: 100