steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ts-cloud-factory-poc/github.com/santosh-sahoo334/superset-analytics-ui:${COMMIT_SHA}', '-m','4g','.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ts-cloud-factory-poc/github.com/santosh-sahoo334/superset-analytics-ui:${COMMIT_SHA}']
timeout: 9000s
options:
 machineType: N1_HIGHCPU_8
 diskSizeGb: 100